name: GitHub Actions Demo
on:
#  pull_request:
#    types: [ opened ]
  workflow_dispatch:
    inputs:
      type: event-type
      user: actor
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event, from user ${{ github.event.inputs.user }}."
