name: GitHub Actions Demo
on:
  workflow_dispatch:
    inputs:
      event-type:
        required: true
        type: string
      user:
        required: true
        type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event, from user ${{ github.event.inputs.user }}."
